engines:
  # tslint:
  #   enabled: true
  #   channel: beta
  #   config: tslint.json
  fixme:
    enabled: true
ratings:
  paths:
    "src/**/*.ts"
exclude_paths:
- "**.d.ts"
- "**.txt"
- "**.js"
- "**.md"
- "**/esdoc.helper.ts"
- "dist/**"
- "docs/**"
- "manual/**"
