sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
addons:
  firefox: "latest"
node_js:
  - '5.4'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
  - npm install -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/jspm install
script:
  - npm run test:travis
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
