language: node_js
node_js:
  - "5.3"
  - "4.2"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - ./node_modules/.bin/jspm install
script:
  - npm run build
  - npm run test:travis
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
