sudo: required
dist: trusty
language: node_js
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper-.*$/
addons:
  apt:
    packages:
      - google-chrome-stable
node_js:
  - "7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install uws
  - npm install -g codeclimate-test-reporter
script:
  - npm run test:travis
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
