sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.4'
before_install:
  - npm i -g npm@^3.0.0
install:
  - sudo apt-get install libxss1 libappindicator1 libindicator7
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - npm prune
  - npm install -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - ./node_modules/.bin/jspm install
script:
  - npm run test:travis
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
